name: kenya_it_hardware
description: A new ecommerce project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animation_director: ^0.1.1
  animations: ^1.1.2
  auto_route: ^0.6.7
  cached_network_image: ^2.4.1
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  dart_random_choice: ^0.0.2
  dartz: ^0.9.2
  division: ^0.8.8
  firebase_auth: ^0.18.4+1
  firebase_storage: ^5.2.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_blurhash: ^0.5.0
  flutter_staggered_animations: ^0.1.2
  form_field_validator: ^1.0.1
  freezed_annotation: ^0.11.0
  get_it: ^5.0.1
  google_sign_in: ^4.5.6
  image_picker: ^0.6.7+14
  injectable: ^1.0.5
  kt_drawer_menu: ^0.0.6
  line_awesome_flutter: ^1.0.1
  line_awesome_icons: ^1.0.4+2
  loading_animations: ^2.1.0
  page_view_indicators: ^1.4.0
  responsive_widgets: ^2.0.1
  rxdart: ^0.23.1
  shared_preferences: ^0.5.12+4
  smart_form: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.0
  device_preview: ^0.4.8
  freezed: ^0.11.4
  injectable_generator: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/one_onboarding.png
    - assets/images/two_onboarding.png
    - assets/images/three_onboarding.png
    - assets/images/banners/2855.jpg
    - assets/images/banners/2865.jpg
    - assets/images/banners/4695212.jpg
    - assets/images/banners/4747177.jpg
    - assets/images/banners/bannerad1.png
    - assets/images/banners/bannerad2.png
    - assets/images/banners/samsunga20.png
    - assets/images/banners/inifinixhot9.png
    - assets/images/categoryicons/Accessories.png
    - assets/images/categoryicons/CPUs.png
    - assets/images/categoryicons/Harddrives.png

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Black.otf
          weight: 900
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Heavy.otf
          weight: 800
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Medium.otf
          weight: 500
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/Avenir_Next_Pro/AvenirLTStd-Light.otf
          weight: 300
